Mark the partition as bootable
qloader2/qloader2 pull request #17
Opened 2020-08-25 21:50 UTC by atomicbitty

Some BIOSes (eg. my laptop's) require at least one partition to be marked as bootable, this patch can save one from frustration.

2020-08-25 22:24 UTC, VisualDevelopment requested changes

2020-08-25 22:24 UTC, VisualDevelopment commented on README.md
> +parted -s loader.img set 1 boot on
The image is called test.img, not loader.img

2020-08-25 22:25 UTC, atomicbitty commented
Sorry for the mistake

2020-08-25 22:26 UTC, VisualDevelopment approved these changes
:+1: Looks good to me!

2020-08-25 22:54 UTC, mintsuki commented
Thank you @atomicbitty and @VisualDevelopment and WOW I cannot believe how terrible BIOSes can be. BIOSes should not care about the partition table, but alas they do, and it can be very annoying.

I suggest it be specified with a comment that setting an active partition is a workarond for potentially buggy BIOSes rather than something that qloader2 actually cares about.

Other than that, LGTM

2020-08-25 23:09 UTC, VisualDevelopment commented on README.md
> +parted -s test.img set 1 boot on
```suggestion
parted -s test.img set 1 boot on # Workaround for buggy BIOSes
```

2020-08-25 23:12 UTC, VisualDevelopment commented
Also, @mintsuki wait till you see the BIOSes that need some weird jmp at the start to mark the boot sector as valid :^)

2020-08-25 23:16 UTC, atomicbitty commented
@mintsuki some bios are way worse, some set the boot disk number to 0x00 with hard disks (it actually happened with a laptop which I tested - laptops have horrible bioses) and it results to disk read error. I may send another pull request for that.

2020-08-25 23:17 UTC, VisualDevelopment commented
> @mintsuki some bios are way worse, some set the boot disk number to 0x00 with hard disks (it actually happened with a laptop which I tested - laptops have horrible bioses) and it results to disk read error. I may send another pull request for that.

I actually noticed a workaround for this in GRUB code

2020-08-25 23:18 UTC, atomicbitty commented
yeah, i've done this exact same workaround in my bootloader.

2020-08-25 23:21 UTC, merged

2020-08-25 23:23 UTC, mintsuki commented
> @mintsuki some bios are way worse, some set the boot disk number to 0x00 with hard disks (it actually happened with a laptop which I tested - laptops have horrible bioses) and it results to disk read error. I may send another pull request for that.

Sure feel free to send a PR for that too. That is incredibly weird though, AFAIK drive 0 is supposed to be the A: floppy disk drive. Could it be that the BIOS just loads up the bootsector thinking it's a floppy's?

2020-08-25 23:40 UTC, atomicbitty commented
> Could it be that the BIOS just loads up the bootsector thinking it's a floppy's?
Probably not, because I was explicitly saying to the bios to emulate the usb drive as HDD. The problem with most proprietary BIOSes is that they are only tested with Windows and maaaaaybe linux or BSD. And these OSes are already protected against dumb BIOSes, so the bugs are (almost) never noticed.

> BIOSes should not care about the partition table, but alas they do, and it can be very annoying.
All proprietary BIOSes I tested either required a partition table (HDDs) or a BPB (FDDs) in order to boot.

2020-08-26 00:07 UTC, VisualDevelopment commented
I hate hardware vendors lol